name: Preprocessing_tests

on:
  push:
    branches:
      - main
    paths:
      - "task-2-data-preprocessing/**"
  pull_request:
    branches:
      - main
    paths:
      - "task-2-data-preprocessing/**"

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
            cd task-2-data-preprocessing/
            pip install -r requirements.txt

      - name: Run other tests
        run: |
              cd task-2-data-preprocessing/
              python -m unittest discover -s tests -p "*.py"


      - name: Test the main function (fatal)
        run: |
            cd task-2-data-preprocessing/
            python -m unittest tests/test_main.py
